-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1:3306
-- Üretim Zamanı: 12 Haz 2024, 23:32:23
-- Sunucu sürümü: 8.2.0
-- PHP Sürümü: 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `kulaklik_site`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `hakkimda`
--

DROP TABLE IF EXISTS `hakkimda`;
CREATE TABLE IF NOT EXISTS `hakkimda` (
  `id` int NOT NULL AUTO_INCREMENT,
  `baslik` varchar(60) NOT NULL,
  `icerik` text NOT NULL,
  `resim` varchar(255) NOT NULL,
  `zaman` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;

--
-- Tablo döküm verisi `hakkimda`
--

INSERT INTO `hakkimda` (`id`, `baslik`, `icerik`, `resim`, `zaman`) VALUES
(1, 'Odyofilizm', 'Hoş geldiniz!\r\n<br>\r\nOdyofilizm, müziğin ve ses kalitesinin tutkulu savunucularını bir araya getiren bir platformdur. Amacımız, en yüksek ses kalitesine ulaşmak isteyen müzikseverler için en güncel bilgileri, ürün incelemelerini ve uzman tavsiyelerini sunmaktır.\r\n<br>\r\n<br>\r\nBiz Kimiz?\r\n<br>\r\nOdyofilizm ekibi olarak, ses mühendislerinden, müzisyenlere ve tutkulu odyofillere kadar geniş bir yelpazede profesyoneller ve meraklılar topluluğuyuz. Her birimiz, müziğin gücüne inanıyor ve bu tutkuyu sizlerle paylaşmaktan büyük mutluluk duyuyoruz. Sitemizde yer alan içeriklerin her biri, yılların getirdiği bilgi birikimi ve deneyimle hazırlanmıştır.\r\n<br>\r\n<br>\r\nMisyonumuz\r\n<br>\r\nMisyonumuz, müzik dinleme deneyiminizi bir üst seviyeye taşımaktır. İster yeni başlayan bir odyofil olun, ister deneyimli bir ses tutkunu, size en doğru bilgileri sunarak en iyi ses ekipmanlarını bulmanıza yardımcı olmayı hedefliyoruz. Sitemizde, en yeni teknolojilerden klasik ekipmanlara kadar geniş bir yelpazede incelemeler bulabilirsiniz.\r\n<br>\r\n<br>\r\nNeler Sunuyoruz?\r\n<br>\r\nÜrün İncelemeleri: Kulaklıklar, hoparlörler, amplifikatörler ve daha birçok ses ekipmanının detaylı incelemelerini sunuyoruz.\r\n<br>\r\n<br>\r\nKılavuzlar ve Rehberler: Doğru ekipmanı seçmenize yardımcı olacak kapsamlı kılavuzlar ve rehberler hazırlıyoruz.\r\n<br>\r\n<br>\r\nHaberler ve Güncellemeler: Ses dünyasındaki en son gelişmeleri ve trendleri takip ederek, sizi güncel tutuyoruz.\r\n<br>\r\n<br>\r\nTopluluk: Forumlarımızda ve sosyal medya platformlarımızda, diğer odyofillerle bağlantı kurabilir, deneyimlerinizi paylaşabilir ve sorularınıza yanıt bulabilirsiniz.\r\n<br>\r\n<br>\r\nNeden Biz?\r\n<br>\r\nOdyofilizm olarak, kaliteli müziğin ve doğru ekipmanın hayatınıza katacağı değerin farkındayız. Bu yüzden, size en doğru ve güvenilir bilgiyi sunmayı önemsiyoruz. İncelemelerimiz ve rehberlerimiz tarafsızdır ve sadece sizlerin memnuniyetini göz önünde bulundurarak hazırlanmıştır.\r\n<br>\r\n<br>\r\nBize Ulaşın\r\n<br>\r\nSorularınız, önerileriniz veya sadece paylaşmak istediğiniz bir deneyiminiz mi var? Bizimle iletişime geçmekten çekinmeyin. İletişim sayfamızdan veya sosyal medya hesaplarımızdan bize ulaşabilirsiniz. Sizlerin görüşleri, bizim için çok değerlidir.\r\n<br>\r\n<br>\r\nOdyofilizm Ekibi', '../image/IMG_3294-2.jpg', '2024-06-12 20:27:44');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kisisel2`
--

DROP TABLE IF EXISTS `kisisel2`;
CREATE TABLE IF NOT EXISTS `kisisel2` (
  `id` int NOT NULL,
  `mail` varchar(120) NOT NULL,
  `numara` varchar(14) NOT NULL,
  `adres` tinytext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

--
-- Tablo döküm verisi `kisisel2`
--

INSERT INTO `kisisel2` (`id`, `mail`, `numara`, `adres`) VALUES
(1, 'beratbesgul77@gmail.com', '0534 636 99 96', 'Kurtuluş Mahallesi, 5060 Sokak, Pınar Apart 4/1 Balıkesir/Gönen');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kulakliklar`
--

DROP TABLE IF EXISTS `kulakliklar`;
CREATE TABLE IF NOT EXISTS `kulakliklar` (
  `id` smallint NOT NULL AUTO_INCREMENT,
  `baslik` varchar(40) NOT NULL,
  `icerik` text NOT NULL,
  `resim` varchar(255) NOT NULL,
  `zaman` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb3;

--
-- Tablo döküm verisi `kulakliklar`
--

INSERT INTO `kulakliklar` (`id`, `baslik`, `icerik`, `resim`, `zaman`) VALUES
(31, 'Hifiman HE400se', 'Hifiman HE400se, bütçe dostu planar manyetik kulaklıklar arasında öne çıkan bir modeldir. Hafif yapısı ve rahat tasarımı, uzun dinleme seansları için idealdir. Yastıkları oldukça konforludur ve baş bandı, baskıyı dengeli bir şekilde dağıtarak rahatsızlığı önler. Ses kalitesine gelince, HE400se geniş bir sahne ve detaylı bir ses sunar. Baslar derin ve kontrollüdür, midler net ve doğal, tizler ise parlak ve genişletilmiş bir frekans aralığına sahiptir. Planar manyetik sürücüler, hızlı tepki süresi ve düşük distorsiyon ile karakterize edilir, bu da karmaşık müzik parçalarını bile temiz ve ayrıntılı bir şekilde dinlemenizi sağlar. 25 ohm empedans ile HE400se, hem taşınabilir cihazlarda hem de amplifikatörlerle kullanım için uygundur. Ancak, tam potansiyelini ortaya çıkarmak için güçlü bir amplifikatörle desteklemek en iyisidir. Fiyat-performans oranı göz önüne alındığında, Hifiman HE400se müzik tutkunları ve audiofiller için harika bir seçimdir. Dayanıklı yapısı ve üstün ses kalitesiyle, bu kulaklıklar hem yeni başlayanlar hem de deneyimli kullanıcılar için tatmin edici bir deneyim sunar. Bu nedenle, Hifiman HE400se, planar manyetik kulaklık dünyasına giriş yapmak isteyenler için mükemmel bir tercih olarak öne çıkmaktadır.', '../image/he400se.jpeg', '2024-06-12 21:35:34'),
(32, 'Sennheiser HD650 ', 'Sennheiser HD650, ses tutkunları arasında uzun zamandır saygın bir yer edinmiş bir referans kulaklıktır. Açık arka tasarımı, geniş ve doğal bir ses sahnesi sunar, bu da özellikle canlı kayıtlar ve klasik müzik dinlerken büyük bir avantaj sağlar. HD650\'nin sürücülerinde kullanılan özel yapım akustik ipek, frekans aralığının genişliğini artırırken distorsiyonu %0,05\'e kadar düşürür. Kulaklığın bas tepkisi, derin ve kontrollü olup midler ise pürüzsüz ve net bir şekilde öne çıkar. Tizler, detaylı ve parlak olup uzun dinleme seanslarında yormayan bir yapıya sahiptir. 300 ohm empedans ile HD650, özellikle yüksek kaliteli amplifikatörlerle eşleştirildiğinde tam potansiyeline ulaşır. Konfor açısından, HD650 geniş ve yumuşak kulak yastıkları ile uzun süreli kullanım için idealdir. Baş bandı, mükemmel bir uyum ve denge sağlar. Yapısal olarak dayanıklı olan bu kulaklık, uzun yıllar boyunca güvenle kullanılabilir. Estetik olarak da şık ve zarif bir tasarıma sahip olan HD650, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de göz doldurur. Sonuç olarak, Sennheiser HD650, müzik tutkunları ve profesyoneller için vazgeçilmez bir referans kulaklığıdır ve geniş ses sahnesi, detaylı ses karakteri ve üstün konforuyla audiofil dünyasında bir ikon haline gelmiştir.', '../image/hd650.jpg', '2024-06-12 21:35:38'),
(33, 'Audeze LCD-5', 'Audeze LCD-5, üst düzey planar manyetik kulaklıklar arasında yer alan ve mükemmel ses kalitesi ile dikkat çeken bir modeldir. Öncelikle, bu kulaklıkların yapısında kullanılan karbon fiber ve magnezyum, hafiflik ve dayanıklılığı bir araya getirir. LCD-5\'in ergonomik tasarımı, uzun dinleme seanslarında bile maksimum konfor sağlar. Ses kalitesi açısından, LCD-5 geniş ve derin bir ses sahnesi sunar. Baslar sıkı ve derindir, midler olağanüstü netlikte ve doğal, tizler ise inanılmaz derecede detaylı ve genişletilmiş bir frekans aralığına sahiptir. Audeze\'nin yeni Fluxor manyetik teknolojisi, daha hızlı ve hassas bir ses üretimi sağlar. Empedansı 14 ohm olan bu kulaklıklar, taşınabilir cihazlarla da kullanılabilir, ancak en iyi performans için yüksek kaliteli bir amplifikatör önerilir. Audeze LCD-5, özellikle profesyonel müzisyenler ve ses mühendisleri için tasarlanmıştır, ancak audiofiller için de eşsiz bir dinleme deneyimi sunar. Yapısal olarak, bu kulaklıklar sağlam ve şık bir tasarıma sahiptir. Özel yastıkları ve baş bandı, rahat bir uyum ve denge sağlar. LCD-5, müzikte en ince detayları bile yakalayabilen üstün bir kulaklıktır. Bu nedenle, Audeze LCD-5, mükemmeliyetçi müzik tutkunları ve profesyoneller için ideal bir seçimdir ve ses kalitesi, konfor ve dayanıklılık açısından beklentileri fazlasıyla karşılar.', '../image/audeze.png', '2024-06-12 21:35:58'),
(34, 'Focal Clear MG', 'Focal Clear MG, dinleyiciye olağanüstü bir ses deneyimi sunmak için tasarlanmış, yüksek kaliteli bir kulaklıktır. Açık arka tasarımı, geniş ve havadar bir ses sahnesi sağlar, bu da müziğin her detayını canlı bir şekilde hissetmenizi sağlar. Clear MG, magnezyum sürücülerle donatılmıştır, bu sürücüler hızlı ve doğru bir ses tepkisi sunarak müziğin dinamiklerini mükemmel bir şekilde yakalar. Baslar güçlü ve derin, midler net ve doğal, tizler ise detaylı ve genişletilmiş bir frekans aralığına sahiptir. 55 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarla hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, Clear MG, mikro delikli sünger yastıkları ve baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Kulak yastıkları, kulak çevresine mükemmel uyum sağlar ve basıncı eşit olarak dağıtır. Yapısal olarak, Focal Clear MG, dayanıklı alüminyum ve deri malzemelerle üretilmiştir, bu da hem sağlamlık hem de estetik açıdan mükemmellik sunar. Şık ve modern tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de dikkat çeker. Focal Clear MG, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve ses performansı, konfor ve dayanıklılık açısından beklentileri fazlasıyla karşılar. Sonuç olarak, Focal Clear MG, üst düzey bir dinleme deneyimi sunar ve müziğin her ayrıntısını kusursuz bir şekilde ileterek dinleyiciyi büyüler.', '../image/Focal.jpeg', '2024-06-12 20:57:48'),
(35, 'Hifiman Sundara (Closed-Back)', 'Hifiman Sundara (Closed-Back), kapalı arka tasarımıyla dış gürültüyü minimuma indirerek izole bir dinleme deneyimi sunar. Bu kulaklık, konforlu ve hafif yapısıyla uzun dinleme seansları için idealdir. Sundara\'nın sürücüleri, geniş frekans aralığı ve düşük distorsiyon ile mükemmel bir ses kalitesi sağlar. Baslar derin ve güçlü, midler temiz ve detaylı, tizler ise parlak ve genişletilmiş bir aralığa sahiptir. Kapalı arka tasarım, ses sızıntısını azaltır ve daha odaklı bir dinleme sağlar. 37 ohm empedans ile Sundara, hem taşınabilir cihazlarda hem de amplifikatörlerle kullanılabilir, ancak tam potansiyeline ulaşmak için güçlü bir amplifikatör önerilir. Kulak yastıkları ve baş bandı, rahat bir uyum ve uzun süreli kullanım için tasarlanmıştır. Yapısal olarak dayanıklı olan Sundara, şık ve modern bir görünüme sahiptir. Hifiman\'ın yenilikçi teknolojileri, bu kulaklıkta yüksek performans ve dayanıklılığı bir araya getirir. Sundara, her tür müzik için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Hifiman Sundara (Closed-Back), müzik tutkunları ve profesyoneller için ideal bir seçimdir ve kapalı arka tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker.', '../image/sundara.jpeg', '2024-06-12 20:57:53'),
(36, 'AKG K712 Pro', 'AKG K712 Pro, profesyonel ses mühendisleri ve müzik tutkunları için tasarlanmış bir referans kulaklıktır. Açık arka tasarımı, geniş ve doğal bir ses sahnesi sunar, bu da özellikle miks ve mastering işlemlerinde büyük bir avantaj sağlar. 3D kulak yastıkları, üstün konfor ve mükemmel bir uyum sağlar, uzun süreli dinleme seansları için idealdir. K712 Pro\'nun ses kalitesi, nötr ve doğru bir şekilde ayarlanmıştır. Baslar sıkı ve kontrollü, midler net ve doğal, tizler ise detaylı ve parlaktır. 62 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarda hem de yüksek kaliteli amplifikatörlerde kullanım için uygundur. K712 Pro, geniş frekans aralığı ve düşük distorsiyon ile dikkat çeker, bu da her tür müzik için ideal bir dinleme deneyimi sunar. Yapısal olarak dayanıklı olan bu kulaklık, hafif ve sağlam malzemelerle üretilmiştir. Şık ve profesyonel tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de göz doldurur. AKG K712 Pro, müzik prodüksiyonu, miks ve mastering için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile kullanıcıyı memnun eder. Sonuç olarak, AKG K712 Pro, profesyonel kullanıcılar ve müzik tutkunları için vazgeçilmez bir referans kulaklıktır ve geniş ses sahnesi, detaylı ses karakteri ve üstün konforuyla audiofil dünyasında saygın bir yer edinmiştir.', '../image/K712pro.jpg', '2024-06-12 20:57:57'),
(37, 'Sivga Phoenix', 'Sivga Phoenix, zarif tasarımı ve üstün ses kalitesi ile dikkat çeken bir kulaklıktır. Ahşap kaplaması ve metal bileşenleri, bu kulaklığa hem sağlamlık hem de estetik bir görünüm kazandırır. Phoenix\'in açık arka tasarımı, geniş ve doğal bir ses sahnesi sağlar. Ses kalitesi açısından, Phoenix dengeli ve zengin bir ses sunar. Baslar derin ve güçlü, midler net ve doğal, tizler ise detaylı ve parlaktır. 32 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarda hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, Sivga Phoenix yumuşak deri kulak yastıkları ve ayarlanabilir baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Yapısal olarak dayanıklı olan bu kulaklık, kaliteli malzemelerle üretilmiştir ve uzun ömürlü kullanım sunar. Şık ve modern tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de göz doldurur. Sivga Phoenix, her tür müzik için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Sivga Phoenix, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve zarif tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir.', '../image/sivga.jpeg', '2024-06-12 20:58:04'),
(38, 'Audio-Technica ATH-AWKT', 'Audio-Technica ATH-AWKT, üst düzey bir kapalı arka kulaklık olup, olağanüstü ses kalitesi ve lüks tasarımıyla dikkat çeker. Bu kulaklık, Japonya\'nın geleneksel ahşap işçiliği kullanılarak üretilmiş olup, yüksek kaliteli Kirishima kiraz ağacı kaplamasıyla estetik açıdan büyüleyicidir. ATH-AWKT, 53 mm\'lik geniş sürücüleri sayesinde geniş frekans aralığı ve düşük distorsiyon sunar. Baslar derin ve sıkı, midler doğal ve net, tizler ise detaylı ve parlaktır. 48 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarla hem de yüksek kaliteli amplifikatörlerle uyumludur. Konfor açısından, ATH-AWKT yumuşak deri kulak yastıkları ve ergonomik baş bandı ile uzun dinleme seanslarında bile rahatlık sağlar. Kulak yastıkları, kulağa mükemmel uyum sağlar ve basıncı eşit olarak dağıtarak rahat bir dinleme deneyimi sunar. Yapısal olarak dayanıklı olan bu kulaklık, premium malzemelerle üretilmiştir ve uzun ömürlü kullanım sunar. Şık ve lüks tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de dikkat çeker. Audio-Technica ATH-AWKT, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve mükemmel ses performansı, konfor ve dayanıklılığı ile beklentileri fazlasıyla karşılar. Sonuç olarak, ATH-AWKT, yüksek kaliteli bir dinleme deneyimi sunar ve müziğin her ayrıntısını kusursuz bir şekilde ileterek dinleyiciyi büyüler.', '../image/awkt.jpeg', '2024-06-12 20:58:32'),
(39, 'Denon D2000', 'Denon D2000, kapalı arka tasarımı ve üstün ses kalitesi ile bilinen bir kulaklıktır. Bu kulaklık, konforlu yapısı ve yüksek performanslı sürücüleri ile dikkat çeker. D2000\'in 50 mm\'lik sürücüleri, geniş bir frekans aralığı ve düşük distorsiyon sunar. Baslar derin ve güçlü, midler net ve doğal, tizler ise detaylı ve parlaktır. 25 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarla hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, D2000 yumuşak deri kulak yastıkları ve ayarlanabilir baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Yapısal olarak dayanıklı olan bu kulaklık, kaliteli malzemelerle üretilmiştir ve uzun ömürlü kullanım sunar. Şık ve modern tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de göz doldurur. Denon D2000, her tür müzik için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Denon D2000, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve kapalı arka tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir.\r\n\r\nMeze Audio 99 Classics\r\nMeze Audio 99 Classics, zarif tasarımı ve üstün ses kalitesi ile dikkat çeken bir kulaklıktır. Ahşap kaplaması ve metal bileşenleri, bu kulaklığa hem sağlamlık hem de estetik bir görünüm kazandırır. 99 Classics\'in kapalı arka tasarımı, dış gürültüyü minimuma indirerek izole bir dinleme deneyimi sunar. Ses kalitesi açısından, 99 Classics dengeli ve zengin bir ses sunar. Baslar derin ve güçlü, midler net ve doğal, tizler ise detaylı ve parlaktır. 32 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarla hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, Meze 99 Classics yumuşak deri kulak yastıkları ve ayarlanabilir baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Yapısal olarak dayanıklı olan bu kulaklık, kaliteli malzemelerle üretilmiştir ve uzun ömürlü kullanım sunar. Şık ve modern tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de göz doldurur. Meze Audio 99 Classics, her tür müzik için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Meze Audio 99 Classics, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve zarif tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir.', '../image/denon.jpeg', '2024-06-12 20:58:38'),
(40, 'Bang & Olufsen Beoplay', 'Bang & Olufsen Beoplay, şık tasarımı ve üstün ses kalitesi ile dikkat çeken bir kulaklık serisidir. Beoplay kulaklıklar, zarif ve modern bir görünüm sunar, yüksek kaliteli malzemelerle üretilmiştir ve dayanıklılığı garanti eder. Ses kalitesi açısından, Beoplay kulaklıklar geniş ve detaylı bir ses sunar. Baslar güçlü ve derin, midler net ve doğal, tizler ise detaylı ve genişletilmiş bir frekans aralığına sahiptir. Empedans ve sürücü boyutları modelden modele değişiklik gösterebilir, bu da farklı dinleme ihtiyaçlarına hitap eder. Konfor açısından, Beoplay kulaklıklar yumuşak deri kulak yastıkları ve ayarlanabilir baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Kulak yastıkları, kulağa mükemmel uyum sağlar ve basıncı eşit olarak dağıtarak rahat bir dinleme deneyimi sunar. Beoplay serisi, hem taşınabilir cihazlarla hem de amplifikatörlerle uyumludur, bu da kullanıcıların her yerde yüksek kaliteli ses deneyimi yaşamasını sağlar. Şık ve modern tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de dikkat çeker. Bang & Olufsen Beoplay, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve mükemmel ses performansı, konfor ve dayanıklılığı ile beklentileri fazlasıyla karşılar. Sonuç olarak, Beoplay kulaklıklar, yüksek kaliteli bir dinleme deneyimi sunar ve müziğin her ayrıntısını kusursuz bir şekilde ileterek dinleyiciyi büyüler.', '../image/beoplay.jpeg', '2024-06-12 20:58:49'),
(41, 'Bowers & Wilkins PX7', 'Bowers & Wilkins PX7, yüksek kaliteli ses ve ileri teknoloji ile donatılmış bir kulaklıktır. Bu kulaklık, aktif gürültü engelleme (ANC) özelliği ile dış dünyadan tamamen izole olmanızı sağlar. PX7, karbon fiber bileşenlerle güçlendirilmiş bir yapı sunar, bu da dayanıklılık ve hafiflik sağlar. 43 mm\'lik sürücüleri, geniş bir frekans aralığı ve düşük distorsiyon ile mükemmel bir ses kalitesi sunar. Baslar güçlü ve derin, midler net ve doğal, tizler ise detaylı ve parlaktır. PX7, 25 saatlik uzun pil ömrü ile kesintisiz müzik keyfi sunar. Ayrıca, hızlı şarj özelliği sayesinde sadece 15 dakikalık şarj ile 5 saatlik kullanım sağlar. Konfor açısından, PX7 yumuşak kulak yastıkları ve ayarlanabilir baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Yapısal olarak dayanıklı olan bu kulaklık, şık ve modern bir görünüme sahiptir. Bluetooth 5.0 teknolojisi ile kablosuz özgürlüğün tadını çıkarabilirsiniz ve aptX Adaptive codec ile yüksek kaliteli ses iletimi sağlanır. Bowers & Wilkins PX7, her tür müzik için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, PX7, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve üstün ses kalitesi, konfor ve dayanıklılığı ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir.', '../image/px7.jpg', '2024-06-12 20:59:11'),
(42, 'Campfire Audio Bonneville', 'Campfire Audio Bonneville, el yapımı kalitesi ve üstün ses performansı ile dikkat çeken bir kulak içi monitördür. Bu kulaklık, titizlikle tasarlanmış bir yapıya sahiptir ve yüksek kaliteli malzemelerle üretilmiştir. Bonneville\'in sürücüleri, geniş bir frekans aralığı ve düşük distorsiyon sunar. Baslar derin ve güçlü, midler net ve doğal, tizler ise detaylı ve parlaktır. 16 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarla hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, Bonneville yumuşak silikon ve köpük uçlarla birlikte gelir, bu da kulağa mükemmel uyum sağlar ve uzun süreli dinleme seanslarında bile rahatlık sunar. Yapısal olarak dayanıklı olan bu kulaklık, şık ve modern bir tasarıma sahiptir. Campfire Audio\'nun yenilikçi teknolojileri, Bonneville\'de yüksek performans ve dayanıklılığı bir araya getirir. Her tür müzik için mükemmel bir seçim olan Bonneville, detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Campfire Audio Bonneville, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve zarif tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir. Campfire Audio Bonneville, müziğin keyfini en üst düzeyde yaşamak isteyenler için tasarlanmış, üstün performanslı bir kulak içi monitördür.', '../image/bonneville.jpeg', '2024-06-12 20:59:20'),
(43, 'Campfire Audio Andromeda', 'Campfire Audio Andromeda, üstün ses kalitesi ve el yapımı tasarımıyla bilinen bir kulak içi monitördür. Bu kulaklık, beş dengeli armatür sürücü ile donatılmış olup, geniş bir frekans aralığı ve düşük distorsiyon sunar. Baslar derin ve güçlü, midler net ve doğal, tizler ise detaylı ve parlaktır. Andromeda, 12.8 ohm empedans ile hem taşınabilir cihazlarla hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, Andromeda yumuşak silikon ve köpük uçlarla birlikte gelir, bu da kulağa mükemmel uyum sağlar ve uzun süreli dinleme seanslarında bile rahatlık sunar. Yapısal olarak dayanıklı olan bu kulaklık, anodize alüminyum kasası ile şık ve modern bir tasarıma sahiptir. Campfire Audio\'nun yenilikçi teknolojileri, Andromeda\'da yüksek performans ve dayanıklılığı bir araya getirir. Her tür müzik için mükemmel bir seçim olan Andromeda, detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Campfire Audio Andromeda, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve zarif tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir. Campfire Audio Andromeda, müziğin keyfini en üst düzeyde yaşamak isteyenler için tasarlanmış, üstün performanslı bir kulak içi monitördür ve detaylı ses reprodüksiyonu ile dinleyiciyi büyüler.', '../image/andromeda.jpeg', '2024-06-12 20:59:24'),
(44, 'Meze Audio 99 Classics', 'Meze Audio 99 Classics, zarif tasarımı ve üstün ses kalitesi ile dikkat çeken bir kulaklıktır. Ahşap kaplaması ve metal bileşenleri, bu kulaklığa hem sağlamlık hem de estetik bir görünüm kazandırır. 99 Classics\'in kapalı arka tasarımı, dış gürültüyü minimuma indirerek izole bir dinleme deneyimi sunar. Ses kalitesi açısından, 99 Classics dengeli ve zengin bir ses sunar. Baslar derin ve güçlü, midler net ve doğal, tizler ise detaylı ve parlaktır. 32 ohm empedans ile bu kulaklıklar, hem taşınabilir cihazlarla hem de amplifikatörlerle kullanım için uygundur. Konfor açısından, Meze 99 Classics yumuşak deri kulak yastıkları ve ayarlanabilir baş bandı ile uzun süreli dinleme seanslarında bile rahatlık sağlar. Yapısal olarak dayanıklı olan bu kulaklık, kaliteli malzemelerle üretilmiştir ve uzun ömürlü kullanım sunar. Şık ve modern tasarımı, sadece ses kalitesiyle değil, aynı zamanda görünümüyle de göz doldurur. Meze Audio 99 Classics, her tür müzik için mükemmel bir seçimdir ve detaylı ses reprodüksiyonu ile dinleyiciyi memnun eder. Sonuç olarak, Meze Audio 99 Classics, müzik tutkunları ve profesyoneller için ideal bir seçimdir ve zarif tasarımı, mükemmel ses kalitesi ve konforu ile dikkat çeker. Bu kulaklık, müziği her ayrıntısıyla hissetmek isteyenler için vazgeçilmez bir seçenek sunar ve ses tutkunları arasında saygın bir yer edinmiştir.', '../image/Meze99.jpg', '2024-06-12 20:59:27');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kullanicilar`
--

DROP TABLE IF EXISTS `kullanicilar`;
CREATE TABLE IF NOT EXISTS `kullanicilar` (
  `id` int NOT NULL AUTO_INCREMENT,
  `kullanici_adi` varchar(15) NOT NULL,
  `sifre` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3;

--
-- Tablo döküm verisi `kullanicilar`
--

INSERT INTO `kullanicilar` (`id`, `kullanici_adi`, `sifre`) VALUES
(2, 'yonetici', '$2y$10$I2vQows2L0PsqRb0CIk3U.xJzyFHjadb.6AZTvsrNke4IxK4Z3Kpy');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
